FROM personal-website-base
WORKDIR /app
COPY .Renviron .Renviron
COPY controllers/about.R controllers/about.R
COPY controllers/contact/handlers.R controllers/contact/handlers.R
COPY controllers/contact/send_message.R controllers/contact/send_message.R
COPY controllers/contact/validations.R controllers/contact/validations.R
COPY controllers/home.R controllers/home.R
COPY controllers/mod.R controllers/mod.R
COPY controllers/resume.pdf controllers/resume.pdf
COPY controllers/resume.R controllers/resume.R
COPY controllers/services.R controllers/services.R
COPY docker-compose.yml docker-compose.yml
COPY Dockerfile Dockerfile
COPY Dockerfile.base Dockerfile.base
COPY helpers/env_vars.R helpers/env_vars.R
COPY helpers/mod.R helpers/mod.R
COPY helpers/operators.R helpers/operators.R
COPY index.R index.R
COPY LICENSE LICENSE
COPY middleware/error.R middleware/error.R
COPY middleware/mod.R middleware/mod.R
COPY middleware/redirect.R middleware/redirect.R
COPY public/css/main.css public/css/main.css
COPY public/img/favicons/android-chrome-192x192.png public/img/favicons/android-chrome-192x192.png
COPY public/img/favicons/android-chrome-512x512.png public/img/favicons/android-chrome-512x512.png
COPY public/img/favicons/apple-touch-icon.png public/img/favicons/apple-touch-icon.png
COPY public/img/favicons/favicon-16x16.png public/img/favicons/favicon-16x16.png
COPY public/img/favicons/favicon-32x32.png public/img/favicons/favicon-32x32.png
COPY public/img/favicons/favicon.ico public/img/favicons/favicon.ico
COPY public/img/favicons/site.webmanifest public/img/favicons/site.webmanifest
COPY public/img/hero-bg.jpg public/img/hero-bg.jpg
COPY public/img/me.jpeg public/img/me.jpeg
COPY public/img/skills/digitalocean.svg public/img/skills/digitalocean.svg
COPY public/img/skills/docker.svg public/img/skills/docker.svg
COPY public/img/skills/git.svg public/img/skills/git.svg
COPY public/img/skills/googlecloud.svg public/img/skills/googlecloud.svg
COPY public/img/skills/javascript.svg public/img/skills/javascript.svg
COPY public/img/skills/openapi.svg public/img/skills/openapi.svg
COPY public/img/skills/r.svg public/img/skills/r.svg
COPY public/img/testimonials/humphreys.jpeg public/img/testimonials/humphreys.jpeg
COPY public/img/testimonials/john.png public/img/testimonials/john.png
COPY public/img/testimonials/william.jpeg public/img/testimonials/william.jpeg
COPY public/img/testimonials/zawadi.jpeg public/img/testimonials/zawadi.jpeg
COPY public/js/main.js public/js/main.js
COPY public/js/toastr_options.js public/js/toastr_options.js
COPY public/vendor/aos/aos.cjs.js public/vendor/aos/aos.cjs.js
COPY public/vendor/aos/aos.css public/vendor/aos/aos.css
COPY public/vendor/aos/aos.esm.js public/vendor/aos/aos.esm.js
COPY public/vendor/aos/aos.js public/vendor/aos/aos.js
COPY public/vendor/aos/aos.js.map public/vendor/aos/aos.js.map
COPY public/vendor/bootstrap-icons/bootstrap-icons.css public/vendor/bootstrap-icons/bootstrap-icons.css
COPY public/vendor/bootstrap-icons/bootstrap-icons.json public/vendor/bootstrap-icons/bootstrap-icons.json
COPY public/vendor/bootstrap-icons/bootstrap-icons.min.css public/vendor/bootstrap-icons/bootstrap-icons.min.css
COPY public/vendor/bootstrap-icons/bootstrap-icons.scss public/vendor/bootstrap-icons/bootstrap-icons.scss
COPY public/vendor/bootstrap-icons/fonts/bootstrap-icons.woff public/vendor/bootstrap-icons/fonts/bootstrap-icons.woff
COPY public/vendor/bootstrap-icons/fonts/bootstrap-icons.woff2 public/vendor/bootstrap-icons/fonts/bootstrap-icons.woff2
COPY public/vendor/bootstrap/css/bootstrap-grid.css public/vendor/bootstrap/css/bootstrap-grid.css
COPY public/vendor/bootstrap/css/bootstrap-grid.css.map public/vendor/bootstrap/css/bootstrap-grid.css.map
COPY public/vendor/bootstrap/css/bootstrap-grid.min.css public/vendor/bootstrap/css/bootstrap-grid.min.css
COPY public/vendor/bootstrap/css/bootstrap-grid.min.css.map public/vendor/bootstrap/css/bootstrap-grid.min.css.map
COPY public/vendor/bootstrap/css/bootstrap-grid.rtl.css public/vendor/bootstrap/css/bootstrap-grid.rtl.css
COPY public/vendor/bootstrap/css/bootstrap-grid.rtl.css.map public/vendor/bootstrap/css/bootstrap-grid.rtl.css.map
COPY public/vendor/bootstrap/css/bootstrap-grid.rtl.min.css public/vendor/bootstrap/css/bootstrap-grid.rtl.min.css
COPY public/vendor/bootstrap/css/bootstrap-grid.rtl.min.css.map public/vendor/bootstrap/css/bootstrap-grid.rtl.min.css.map
COPY public/vendor/bootstrap/css/bootstrap-reboot.css public/vendor/bootstrap/css/bootstrap-reboot.css
COPY public/vendor/bootstrap/css/bootstrap-reboot.css.map public/vendor/bootstrap/css/bootstrap-reboot.css.map
COPY public/vendor/bootstrap/css/bootstrap-reboot.min.css public/vendor/bootstrap/css/bootstrap-reboot.min.css
COPY public/vendor/bootstrap/css/bootstrap-reboot.min.css.map public/vendor/bootstrap/css/bootstrap-reboot.min.css.map
COPY public/vendor/bootstrap/css/bootstrap-reboot.rtl.css public/vendor/bootstrap/css/bootstrap-reboot.rtl.css
COPY public/vendor/bootstrap/css/bootstrap-reboot.rtl.css.map public/vendor/bootstrap/css/bootstrap-reboot.rtl.css.map
COPY public/vendor/bootstrap/css/bootstrap-reboot.rtl.min.css public/vendor/bootstrap/css/bootstrap-reboot.rtl.min.css
COPY public/vendor/bootstrap/css/bootstrap-reboot.rtl.min.css.map public/vendor/bootstrap/css/bootstrap-reboot.rtl.min.css.map
COPY public/vendor/bootstrap/css/bootstrap-utilities.css public/vendor/bootstrap/css/bootstrap-utilities.css
COPY public/vendor/bootstrap/css/bootstrap-utilities.css.map public/vendor/bootstrap/css/bootstrap-utilities.css.map
COPY public/vendor/bootstrap/css/bootstrap-utilities.min.css public/vendor/bootstrap/css/bootstrap-utilities.min.css
COPY public/vendor/bootstrap/css/bootstrap-utilities.min.css.map public/vendor/bootstrap/css/bootstrap-utilities.min.css.map
COPY public/vendor/bootstrap/css/bootstrap-utilities.rtl.css public/vendor/bootstrap/css/bootstrap-utilities.rtl.css
COPY public/vendor/bootstrap/css/bootstrap-utilities.rtl.css.map public/vendor/bootstrap/css/bootstrap-utilities.rtl.css.map
COPY public/vendor/bootstrap/css/bootstrap-utilities.rtl.min.css public/vendor/bootstrap/css/bootstrap-utilities.rtl.min.css
COPY public/vendor/bootstrap/css/bootstrap-utilities.rtl.min.css.map public/vendor/bootstrap/css/bootstrap-utilities.rtl.min.css.map
COPY public/vendor/bootstrap/css/bootstrap.css public/vendor/bootstrap/css/bootstrap.css
COPY public/vendor/bootstrap/css/bootstrap.css.map public/vendor/bootstrap/css/bootstrap.css.map
COPY public/vendor/bootstrap/css/bootstrap.min.css public/vendor/bootstrap/css/bootstrap.min.css
COPY public/vendor/bootstrap/css/bootstrap.min.css.map public/vendor/bootstrap/css/bootstrap.min.css.map
COPY public/vendor/bootstrap/css/bootstrap.rtl.css public/vendor/bootstrap/css/bootstrap.rtl.css
COPY public/vendor/bootstrap/css/bootstrap.rtl.css.map public/vendor/bootstrap/css/bootstrap.rtl.css.map
COPY public/vendor/bootstrap/css/bootstrap.rtl.min.css public/vendor/bootstrap/css/bootstrap.rtl.min.css
COPY public/vendor/bootstrap/css/bootstrap.rtl.min.css.map public/vendor/bootstrap/css/bootstrap.rtl.min.css.map
COPY public/vendor/bootstrap/js/bootstrap.bundle.js public/vendor/bootstrap/js/bootstrap.bundle.js
COPY public/vendor/bootstrap/js/bootstrap.bundle.js.map public/vendor/bootstrap/js/bootstrap.bundle.js.map
COPY public/vendor/bootstrap/js/bootstrap.bundle.min.js public/vendor/bootstrap/js/bootstrap.bundle.min.js
COPY public/vendor/bootstrap/js/bootstrap.bundle.min.js.map public/vendor/bootstrap/js/bootstrap.bundle.min.js.map
COPY public/vendor/bootstrap/js/bootstrap.esm.js public/vendor/bootstrap/js/bootstrap.esm.js
COPY public/vendor/bootstrap/js/bootstrap.esm.js.map public/vendor/bootstrap/js/bootstrap.esm.js.map
COPY public/vendor/bootstrap/js/bootstrap.esm.min.js public/vendor/bootstrap/js/bootstrap.esm.min.js
COPY public/vendor/bootstrap/js/bootstrap.esm.min.js.map public/vendor/bootstrap/js/bootstrap.esm.min.js.map
COPY public/vendor/bootstrap/js/bootstrap.js public/vendor/bootstrap/js/bootstrap.js
COPY public/vendor/bootstrap/js/bootstrap.js.map public/vendor/bootstrap/js/bootstrap.js.map
COPY public/vendor/bootstrap/js/bootstrap.min.js public/vendor/bootstrap/js/bootstrap.min.js
COPY public/vendor/bootstrap/js/bootstrap.min.js.map public/vendor/bootstrap/js/bootstrap.min.js.map
COPY public/vendor/glightbox/css/glightbox.css public/vendor/glightbox/css/glightbox.css
COPY public/vendor/glightbox/css/glightbox.min.css public/vendor/glightbox/css/glightbox.min.css
COPY public/vendor/glightbox/js/glightbox.js public/vendor/glightbox/js/glightbox.js
COPY public/vendor/glightbox/js/glightbox.min.js public/vendor/glightbox/js/glightbox.min.js
COPY public/vendor/htmx/htmx-2.0.2.min.js public/vendor/htmx/htmx-2.0.2.min.js
COPY public/vendor/imagesloaded/imagesloaded.pkgd.min.js public/vendor/imagesloaded/imagesloaded.pkgd.min.js
COPY public/vendor/isotope-layout/isotope.pkgd.js public/vendor/isotope-layout/isotope.pkgd.js
COPY public/vendor/isotope-layout/isotope.pkgd.min.js public/vendor/isotope-layout/isotope.pkgd.min.js
COPY public/vendor/jquery/jquery-3.7.1.min.js public/vendor/jquery/jquery-3.7.1.min.js
COPY public/vendor/purecounter/purecounter_vanilla.js public/vendor/purecounter/purecounter_vanilla.js
COPY public/vendor/purecounter/purecounter_vanilla.js.map public/vendor/purecounter/purecounter_vanilla.js.map
COPY public/vendor/swiper/swiper-bundle.min.css public/vendor/swiper/swiper-bundle.min.css
COPY public/vendor/swiper/swiper-bundle.min.js public/vendor/swiper/swiper-bundle.min.js
COPY public/vendor/swiper/swiper-bundle.min.js.map public/vendor/swiper/swiper-bundle.min.js.map
COPY public/vendor/toastr/toastr-2.1.3.min.css public/vendor/toastr/toastr-2.1.3.min.css
COPY public/vendor/toastr/toastr-2.1.3.min.js public/vendor/toastr/toastr-2.1.3.min.js
COPY public/vendor/waypoints/noframework.waypoints.js public/vendor/waypoints/noframework.waypoints.js
COPY README.md README.md
COPY store/about.R store/about.R
COPY store/contact.R store/contact.R
COPY store/create_section_title.R store/create_section_title.R
COPY store/header.R store/header.R
COPY store/home.R store/home.R
COPY store/mod.R store/mod.R
COPY store/page_meta.R store/page_meta.R
COPY store/resume.R store/resume.R
COPY store/services.R store/services.R
COPY store/toastr.R store/toastr.R
COPY templates/page.html templates/page.html
COPY templates/partials/footer.html templates/partials/footer.html
COPY templates/partials/header.html templates/partials/header.html
COPY templates/path.R templates/path.R
EXPOSE 8000
CMD ["Rscript", "index.R"] 
